// MODULE top, AUTOMATICALLY GENERATED BY PYTHON

/**/
`default_nettype wire


module top (
  // rfdc: rfdc
    input adc2_clk_n,
    input adc2_clk_p,
    input sysref_in_n,
    input sysref_in_p,
    input vin0_01_n,
    input vin0_01_p,
    input vin0_23_n,
    input vin0_23_p,
    input vin1_01_n,
    input vin1_01_p,
    input vin1_23_n,
    input vin1_23_p,
    input vin2_01_n,
    input vin2_01_p,
    input vin2_23_n,
    input vin2_23_p,
    input vin3_01_n,
    input vin3_01_p,
    input vin3_23_n,
    input vin3_23_p,
  // rfsoc4x2: RFSoC4x2
    input pl_clk_n,
    input pl_clk_p,
    output mmcm_locked
  );




/*
  _____ _                   _     
 / ____(_)                 | |    
| (___  _  __ _ _ __   __ _| |___ 
 \___ \| |/ _` | '_ \ / _` | / __|
 ____) | | (_| | | | | (_| | \__ \ 
|_____/|_|\__, |_| |_|\__,_|_|___/
          __/ |                  
         |___/                   
*/
  // axi_protocol_converter: axi_protocol_converter0
  wire axil_clk;
  wire axil_rst_n;
  wire [31:0] rfsoc_complex_snapshot_adcsnap0_imag_ctrl_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap0_imag_ctrl_out_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap0_imag_status_in;
  wire [0:0] rfsoc_complex_snapshot_adcsnap0_imag_status_in_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap0_real_ctrl_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap0_real_ctrl_out_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap0_real_status_in;
  wire [0:0] rfsoc_complex_snapshot_adcsnap0_real_status_in_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap1_imag_ctrl_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap1_imag_ctrl_out_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap1_imag_status_in;
  wire [0:0] rfsoc_complex_snapshot_adcsnap1_imag_status_in_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap1_real_ctrl_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap1_real_ctrl_out_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap1_real_status_in;
  wire [0:0] rfsoc_complex_snapshot_adcsnap1_real_status_in_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap2_imag_ctrl_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap2_imag_ctrl_out_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap2_imag_status_in;
  wire [0:0] rfsoc_complex_snapshot_adcsnap2_imag_status_in_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap2_real_ctrl_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap2_real_ctrl_out_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap2_real_status_in;
  wire [0:0] rfsoc_complex_snapshot_adcsnap2_real_status_in_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap3_imag_ctrl_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap3_imag_ctrl_out_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap3_imag_status_in;
  wire [0:0] rfsoc_complex_snapshot_adcsnap3_imag_status_in_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap3_real_ctrl_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap3_real_ctrl_out_we;
  wire [31:0] rfsoc_complex_snapshot_adcsnap3_real_status_in;
  wire [0:0] rfsoc_complex_snapshot_adcsnap3_real_status_in_we;
  wire [31:0] rfsoc_complex_snapshot_board_id_in;
  wire [0:0] rfsoc_complex_snapshot_board_id_in_we;
  wire [31:0] rfsoc_complex_snapshot_clkcounter_in;
  wire [0:0] rfsoc_complex_snapshot_clkcounter_in_we;
  wire [31:0] rfsoc_complex_snapshot_rev_in;
  wire [0:0] rfsoc_complex_snapshot_rev_in_we;
  wire [31:0] rfsoc_complex_snapshot_rev_rcs_in;
  wire [0:0] rfsoc_complex_snapshot_rev_rcs_in_we;
  wire [31:0] rfsoc_complex_snapshot_scratchpad_out;
  wire [0:0] rfsoc_complex_snapshot_scratchpad_out_we;
  wire [31:0] rfsoc_complex_snapshot_snap_trig_out;
  wire [0:0] rfsoc_complex_snapshot_snap_trig_out_we;
  // bram: adcsnap0/imag/bram
  wire [10:0] rfsoc_complex_snapshot_adcsnap0_imag_bram_addr;
  wire [127:0] rfsoc_complex_snapshot_adcsnap0_imag_bram_data_in;
  wire [127:0] rfsoc_complex_snapshot_adcsnap0_imag_bram_data_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap0_imag_bram_we;
  // bram: adcsnap0/real/bram
  wire [10:0] rfsoc_complex_snapshot_adcsnap0_real_bram_addr;
  wire [127:0] rfsoc_complex_snapshot_adcsnap0_real_bram_data_in;
  wire [127:0] rfsoc_complex_snapshot_adcsnap0_real_bram_data_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap0_real_bram_we;
  // bram: adcsnap1/imag/bram
  wire [10:0] rfsoc_complex_snapshot_adcsnap1_imag_bram_addr;
  wire [127:0] rfsoc_complex_snapshot_adcsnap1_imag_bram_data_in;
  wire [127:0] rfsoc_complex_snapshot_adcsnap1_imag_bram_data_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap1_imag_bram_we;
  // bram: adcsnap1/real/bram
  wire [10:0] rfsoc_complex_snapshot_adcsnap1_real_bram_addr;
  wire [127:0] rfsoc_complex_snapshot_adcsnap1_real_bram_data_in;
  wire [127:0] rfsoc_complex_snapshot_adcsnap1_real_bram_data_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap1_real_bram_we;
  // bram: adcsnap2/imag/bram
  wire [10:0] rfsoc_complex_snapshot_adcsnap2_imag_bram_addr;
  wire [127:0] rfsoc_complex_snapshot_adcsnap2_imag_bram_data_in;
  wire [127:0] rfsoc_complex_snapshot_adcsnap2_imag_bram_data_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap2_imag_bram_we;
  // bram: adcsnap2/real/bram
  wire [10:0] rfsoc_complex_snapshot_adcsnap2_real_bram_addr;
  wire [127:0] rfsoc_complex_snapshot_adcsnap2_real_bram_data_in;
  wire [127:0] rfsoc_complex_snapshot_adcsnap2_real_bram_data_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap2_real_bram_we;
  // bram: adcsnap3/imag/bram
  wire [10:0] rfsoc_complex_snapshot_adcsnap3_imag_bram_addr;
  wire [127:0] rfsoc_complex_snapshot_adcsnap3_imag_bram_data_in;
  wire [127:0] rfsoc_complex_snapshot_adcsnap3_imag_bram_data_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap3_imag_bram_we;
  // bram: adcsnap3/real/bram
  wire [10:0] rfsoc_complex_snapshot_adcsnap3_real_bram_addr;
  wire [127:0] rfsoc_complex_snapshot_adcsnap3_real_bram_data_in;
  wire [127:0] rfsoc_complex_snapshot_adcsnap3_real_bram_data_out;
  wire [0:0] rfsoc_complex_snapshot_adcsnap3_real_bram_we;
  // rfdc: rfdc
  wire [39:0] M_AXI_araddr;
  wire [2:0] M_AXI_arprot;
  wire M_AXI_arready;
  wire M_AXI_arvalid;
  wire [39:0] M_AXI_awaddr;
  wire [2:0] M_AXI_awprot;
  wire M_AXI_awready;
  wire M_AXI_awvalid;
  wire M_AXI_bready;
  wire [1:0] M_AXI_bresp;
  wire M_AXI_bvalid;
  wire [31:0] M_AXI_rdata;
  wire M_AXI_rready;
  wire [1:0] M_AXI_rresp;
  wire M_AXI_rvalid;
  wire [31:0] M_AXI_wdata;
  wire M_AXI_wready;
  wire [3:0] M_AXI_wstrb;
  wire M_AXI_wvalid;
  wire axil_arst_n;
  wire axil_rst;
  wire clk_adc0;
  wire clk_adc1;
  wire clk_adc2;
  wire clk_adc3;
  wire m00_axis_tvalid;
  wire m01_axis_tvalid;
  wire m0_axis_aclk;
  wire m10_axis_tvalid;
  wire m11_axis_tvalid;
  wire m1_axis_aclk;
  wire m20_axis_tvalid;
  wire m21_axis_tvalid;
  wire m2_axis_aclk;
  wire m30_axis_tvalid;
  wire m31_axis_tvalid;
  wire m3_axis_aclk;
  wire [31:0] m_axi4lite_rfdc_araddr;
  wire m_axi4lite_rfdc_arready;
  wire m_axi4lite_rfdc_arvalid;
  wire [31:0] m_axi4lite_rfdc_awaddr;
  wire m_axi4lite_rfdc_awready;
  wire m_axi4lite_rfdc_awvalid;
  wire m_axi4lite_rfdc_bready;
  wire [1:0] m_axi4lite_rfdc_bresp;
  wire m_axi4lite_rfdc_bvalid;
  wire [31:0] m_axi4lite_rfdc_rdata;
  wire m_axi4lite_rfdc_rready;
  wire [1:0] m_axi4lite_rfdc_rresp;
  wire m_axi4lite_rfdc_rvalid;
  wire [31:0] m_axi4lite_rfdc_wdata;
  wire m_axi4lite_rfdc_wready;
  wire [3:0] m_axi4lite_rfdc_wstrb;
  wire m_axi4lite_rfdc_wvalid;
  wire pl_sys_clk;
  wire rfdc_irq;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m00_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m01_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m02_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m03_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m10_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m12_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m20_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m21_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m22_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m23_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m30_axis_tdata;
  wire [127:0] rfsoc_complex_snapshot_rfdc_m32_axis_tdata;
  // rfsoc4x2: RFSoC4x2
  wire adc_clk;
  wire adc_clk180;
  wire adc_clk270;
  wire adc_clk90;
  // sw_reg: adcsnap0/imag/ctrl
  wire [31:0] rfsoc_complex_snapshot_adcsnap0_imag_ctrl_user_data_out;
  // sw_reg: adcsnap0/imag/status
  wire [31:0] rfsoc_complex_snapshot_adcsnap0_imag_status_user_data_in;
  // sw_reg: adcsnap0/real/ctrl
  wire [31:0] rfsoc_complex_snapshot_adcsnap0_real_ctrl_user_data_out;
  // sw_reg: adcsnap0/real/status
  wire [31:0] rfsoc_complex_snapshot_adcsnap0_real_status_user_data_in;
  // sw_reg: adcsnap1/imag/ctrl
  wire [31:0] rfsoc_complex_snapshot_adcsnap1_imag_ctrl_user_data_out;
  // sw_reg: adcsnap1/imag/status
  wire [31:0] rfsoc_complex_snapshot_adcsnap1_imag_status_user_data_in;
  // sw_reg: adcsnap1/real/ctrl
  wire [31:0] rfsoc_complex_snapshot_adcsnap1_real_ctrl_user_data_out;
  // sw_reg: adcsnap1/real/status
  wire [31:0] rfsoc_complex_snapshot_adcsnap1_real_status_user_data_in;
  // sw_reg: adcsnap2/imag/ctrl
  wire [31:0] rfsoc_complex_snapshot_adcsnap2_imag_ctrl_user_data_out;
  // sw_reg: adcsnap2/imag/status
  wire [31:0] rfsoc_complex_snapshot_adcsnap2_imag_status_user_data_in;
  // sw_reg: adcsnap2/real/ctrl
  wire [31:0] rfsoc_complex_snapshot_adcsnap2_real_ctrl_user_data_out;
  // sw_reg: adcsnap2/real/status
  wire [31:0] rfsoc_complex_snapshot_adcsnap2_real_status_user_data_in;
  // sw_reg: adcsnap3/imag/ctrl
  wire [31:0] rfsoc_complex_snapshot_adcsnap3_imag_ctrl_user_data_out;
  // sw_reg: adcsnap3/imag/status
  wire [31:0] rfsoc_complex_snapshot_adcsnap3_imag_status_user_data_in;
  // sw_reg: adcsnap3/real/ctrl
  wire [31:0] rfsoc_complex_snapshot_adcsnap3_real_ctrl_user_data_out;
  // sw_reg: adcsnap3/real/status
  wire [31:0] rfsoc_complex_snapshot_adcsnap3_real_status_user_data_in;
  // sw_reg: snap_trig
  wire [31:0] rfsoc_complex_snapshot_snap_trig_user_data_out;
  // sys_block: RFSoC4x2
  wire [31:0] rfsoc_complex_snapshot_clkcounter_cdc;
  wire [0:0] rfsoc_complex_snapshot_clkcounter_we;
  wire user_rst;
  // xsg: RFSoC4x2
  (* keep = "true" *) wire sys_clk;
  (* keep = "true" *) wire user_clk;
  (* keep = "true" *) wire user_clk180;
  (* keep = "true" *) wire user_clk270;
  (* keep = "true" *) wire user_clk90;

/*
  _____           _                            
 |_   _|         | |                           
   | |  _ __  ___| |_ __ _ _ __   ___ ___  ___ 
   | | | '_ \/ __| __/ _` | '_ \ / __/ _ \/ __|
  _| |_| | | \__ \ || (_| | | | | (_|  __/\__ \ 
 |_____|_| |_|___/\__\__,_|_| |_|\___\___||___/
*/
  // axi_protocol_converter: axi_protocol_converter0
  axi4lite_ic_wrapper  axi4lite_interconnect (
    .axi4lite_aclk(axil_clk),
    .axi4lite_adcsnap0_imag_bram_adcsnap0_imag_bram_add(rfsoc_complex_snapshot_adcsnap0_imag_bram_addr),
    .axi4lite_adcsnap0_imag_bram_adcsnap0_imag_bram_clk(user_clk),
    .axi4lite_adcsnap0_imag_bram_adcsnap0_imag_bram_data_in(rfsoc_complex_snapshot_adcsnap0_imag_bram_data_in),
    .axi4lite_adcsnap0_imag_bram_adcsnap0_imag_bram_data_out(rfsoc_complex_snapshot_adcsnap0_imag_bram_data_out),
    .axi4lite_adcsnap0_imag_bram_adcsnap0_imag_bram_en(1'b1),
    .axi4lite_adcsnap0_imag_bram_adcsnap0_imag_bram_we(rfsoc_complex_snapshot_adcsnap0_imag_bram_we),
    .axi4lite_adcsnap0_real_bram_adcsnap0_real_bram_add(rfsoc_complex_snapshot_adcsnap0_real_bram_addr),
    .axi4lite_adcsnap0_real_bram_adcsnap0_real_bram_clk(user_clk),
    .axi4lite_adcsnap0_real_bram_adcsnap0_real_bram_data_in(rfsoc_complex_snapshot_adcsnap0_real_bram_data_in),
    .axi4lite_adcsnap0_real_bram_adcsnap0_real_bram_data_out(rfsoc_complex_snapshot_adcsnap0_real_bram_data_out),
    .axi4lite_adcsnap0_real_bram_adcsnap0_real_bram_en(1'b1),
    .axi4lite_adcsnap0_real_bram_adcsnap0_real_bram_we(rfsoc_complex_snapshot_adcsnap0_real_bram_we),
    .axi4lite_adcsnap1_imag_bram_adcsnap1_imag_bram_add(rfsoc_complex_snapshot_adcsnap1_imag_bram_addr),
    .axi4lite_adcsnap1_imag_bram_adcsnap1_imag_bram_clk(user_clk),
    .axi4lite_adcsnap1_imag_bram_adcsnap1_imag_bram_data_in(rfsoc_complex_snapshot_adcsnap1_imag_bram_data_in),
    .axi4lite_adcsnap1_imag_bram_adcsnap1_imag_bram_data_out(rfsoc_complex_snapshot_adcsnap1_imag_bram_data_out),
    .axi4lite_adcsnap1_imag_bram_adcsnap1_imag_bram_en(1'b1),
    .axi4lite_adcsnap1_imag_bram_adcsnap1_imag_bram_we(rfsoc_complex_snapshot_adcsnap1_imag_bram_we),
    .axi4lite_adcsnap1_real_bram_adcsnap1_real_bram_add(rfsoc_complex_snapshot_adcsnap1_real_bram_addr),
    .axi4lite_adcsnap1_real_bram_adcsnap1_real_bram_clk(user_clk),
    .axi4lite_adcsnap1_real_bram_adcsnap1_real_bram_data_in(rfsoc_complex_snapshot_adcsnap1_real_bram_data_in),
    .axi4lite_adcsnap1_real_bram_adcsnap1_real_bram_data_out(rfsoc_complex_snapshot_adcsnap1_real_bram_data_out),
    .axi4lite_adcsnap1_real_bram_adcsnap1_real_bram_en(1'b1),
    .axi4lite_adcsnap1_real_bram_adcsnap1_real_bram_we(rfsoc_complex_snapshot_adcsnap1_real_bram_we),
    .axi4lite_adcsnap2_imag_bram_adcsnap2_imag_bram_add(rfsoc_complex_snapshot_adcsnap2_imag_bram_addr),
    .axi4lite_adcsnap2_imag_bram_adcsnap2_imag_bram_clk(user_clk),
    .axi4lite_adcsnap2_imag_bram_adcsnap2_imag_bram_data_in(rfsoc_complex_snapshot_adcsnap2_imag_bram_data_in),
    .axi4lite_adcsnap2_imag_bram_adcsnap2_imag_bram_data_out(rfsoc_complex_snapshot_adcsnap2_imag_bram_data_out),
    .axi4lite_adcsnap2_imag_bram_adcsnap2_imag_bram_en(1'b1),
    .axi4lite_adcsnap2_imag_bram_adcsnap2_imag_bram_we(rfsoc_complex_snapshot_adcsnap2_imag_bram_we),
    .axi4lite_adcsnap2_real_bram_adcsnap2_real_bram_add(rfsoc_complex_snapshot_adcsnap2_real_bram_addr),
    .axi4lite_adcsnap2_real_bram_adcsnap2_real_bram_clk(user_clk),
    .axi4lite_adcsnap2_real_bram_adcsnap2_real_bram_data_in(rfsoc_complex_snapshot_adcsnap2_real_bram_data_in),
    .axi4lite_adcsnap2_real_bram_adcsnap2_real_bram_data_out(rfsoc_complex_snapshot_adcsnap2_real_bram_data_out),
    .axi4lite_adcsnap2_real_bram_adcsnap2_real_bram_en(1'b1),
    .axi4lite_adcsnap2_real_bram_adcsnap2_real_bram_we(rfsoc_complex_snapshot_adcsnap2_real_bram_we),
    .axi4lite_adcsnap3_imag_bram_adcsnap3_imag_bram_add(rfsoc_complex_snapshot_adcsnap3_imag_bram_addr),
    .axi4lite_adcsnap3_imag_bram_adcsnap3_imag_bram_clk(user_clk),
    .axi4lite_adcsnap3_imag_bram_adcsnap3_imag_bram_data_in(rfsoc_complex_snapshot_adcsnap3_imag_bram_data_in),
    .axi4lite_adcsnap3_imag_bram_adcsnap3_imag_bram_data_out(rfsoc_complex_snapshot_adcsnap3_imag_bram_data_out),
    .axi4lite_adcsnap3_imag_bram_adcsnap3_imag_bram_en(1'b1),
    .axi4lite_adcsnap3_imag_bram_adcsnap3_imag_bram_we(rfsoc_complex_snapshot_adcsnap3_imag_bram_we),
    .axi4lite_adcsnap3_real_bram_adcsnap3_real_bram_add(rfsoc_complex_snapshot_adcsnap3_real_bram_addr),
    .axi4lite_adcsnap3_real_bram_adcsnap3_real_bram_clk(user_clk),
    .axi4lite_adcsnap3_real_bram_adcsnap3_real_bram_data_in(rfsoc_complex_snapshot_adcsnap3_real_bram_data_in),
    .axi4lite_adcsnap3_real_bram_adcsnap3_real_bram_data_out(rfsoc_complex_snapshot_adcsnap3_real_bram_data_out),
    .axi4lite_adcsnap3_real_bram_adcsnap3_real_bram_en(1'b1),
    .axi4lite_adcsnap3_real_bram_adcsnap3_real_bram_we(rfsoc_complex_snapshot_adcsnap3_real_bram_we),
    .axi4lite_aresetn(axil_rst_n),
    .axi4lite_sw_reg_adcsnap0_imag_ctrl_out(rfsoc_complex_snapshot_adcsnap0_imag_ctrl_out),
    .axi4lite_sw_reg_adcsnap0_imag_ctrl_out_we(rfsoc_complex_snapshot_adcsnap0_imag_ctrl_out_we),
    .axi4lite_sw_reg_adcsnap0_imag_status_in(rfsoc_complex_snapshot_adcsnap0_imag_status_in),
    .axi4lite_sw_reg_adcsnap0_imag_status_in_we(rfsoc_complex_snapshot_adcsnap0_imag_status_in_we),
    .axi4lite_sw_reg_adcsnap0_real_ctrl_out(rfsoc_complex_snapshot_adcsnap0_real_ctrl_out),
    .axi4lite_sw_reg_adcsnap0_real_ctrl_out_we(rfsoc_complex_snapshot_adcsnap0_real_ctrl_out_we),
    .axi4lite_sw_reg_adcsnap0_real_status_in(rfsoc_complex_snapshot_adcsnap0_real_status_in),
    .axi4lite_sw_reg_adcsnap0_real_status_in_we(rfsoc_complex_snapshot_adcsnap0_real_status_in_we),
    .axi4lite_sw_reg_adcsnap1_imag_ctrl_out(rfsoc_complex_snapshot_adcsnap1_imag_ctrl_out),
    .axi4lite_sw_reg_adcsnap1_imag_ctrl_out_we(rfsoc_complex_snapshot_adcsnap1_imag_ctrl_out_we),
    .axi4lite_sw_reg_adcsnap1_imag_status_in(rfsoc_complex_snapshot_adcsnap1_imag_status_in),
    .axi4lite_sw_reg_adcsnap1_imag_status_in_we(rfsoc_complex_snapshot_adcsnap1_imag_status_in_we),
    .axi4lite_sw_reg_adcsnap1_real_ctrl_out(rfsoc_complex_snapshot_adcsnap1_real_ctrl_out),
    .axi4lite_sw_reg_adcsnap1_real_ctrl_out_we(rfsoc_complex_snapshot_adcsnap1_real_ctrl_out_we),
    .axi4lite_sw_reg_adcsnap1_real_status_in(rfsoc_complex_snapshot_adcsnap1_real_status_in),
    .axi4lite_sw_reg_adcsnap1_real_status_in_we(rfsoc_complex_snapshot_adcsnap1_real_status_in_we),
    .axi4lite_sw_reg_adcsnap2_imag_ctrl_out(rfsoc_complex_snapshot_adcsnap2_imag_ctrl_out),
    .axi4lite_sw_reg_adcsnap2_imag_ctrl_out_we(rfsoc_complex_snapshot_adcsnap2_imag_ctrl_out_we),
    .axi4lite_sw_reg_adcsnap2_imag_status_in(rfsoc_complex_snapshot_adcsnap2_imag_status_in),
    .axi4lite_sw_reg_adcsnap2_imag_status_in_we(rfsoc_complex_snapshot_adcsnap2_imag_status_in_we),
    .axi4lite_sw_reg_adcsnap2_real_ctrl_out(rfsoc_complex_snapshot_adcsnap2_real_ctrl_out),
    .axi4lite_sw_reg_adcsnap2_real_ctrl_out_we(rfsoc_complex_snapshot_adcsnap2_real_ctrl_out_we),
    .axi4lite_sw_reg_adcsnap2_real_status_in(rfsoc_complex_snapshot_adcsnap2_real_status_in),
    .axi4lite_sw_reg_adcsnap2_real_status_in_we(rfsoc_complex_snapshot_adcsnap2_real_status_in_we),
    .axi4lite_sw_reg_adcsnap3_imag_ctrl_out(rfsoc_complex_snapshot_adcsnap3_imag_ctrl_out),
    .axi4lite_sw_reg_adcsnap3_imag_ctrl_out_we(rfsoc_complex_snapshot_adcsnap3_imag_ctrl_out_we),
    .axi4lite_sw_reg_adcsnap3_imag_status_in(rfsoc_complex_snapshot_adcsnap3_imag_status_in),
    .axi4lite_sw_reg_adcsnap3_imag_status_in_we(rfsoc_complex_snapshot_adcsnap3_imag_status_in_we),
    .axi4lite_sw_reg_adcsnap3_real_ctrl_out(rfsoc_complex_snapshot_adcsnap3_real_ctrl_out),
    .axi4lite_sw_reg_adcsnap3_real_ctrl_out_we(rfsoc_complex_snapshot_adcsnap3_real_ctrl_out_we),
    .axi4lite_sw_reg_adcsnap3_real_status_in(rfsoc_complex_snapshot_adcsnap3_real_status_in),
    .axi4lite_sw_reg_adcsnap3_real_status_in_we(rfsoc_complex_snapshot_adcsnap3_real_status_in_we),
    .axi4lite_sw_reg_snap_trig_out(rfsoc_complex_snapshot_snap_trig_out),
    .axi4lite_sw_reg_snap_trig_out_we(rfsoc_complex_snapshot_snap_trig_out_we),
    .axi4lite_sys_board_id_in(rfsoc_complex_snapshot_board_id_in),
    .axi4lite_sys_board_id_in_we(rfsoc_complex_snapshot_board_id_in_we),
    .axi4lite_sys_clkcounter_in(rfsoc_complex_snapshot_clkcounter_in),
    .axi4lite_sys_clkcounter_in_we(rfsoc_complex_snapshot_clkcounter_in_we),
    .axi4lite_sys_rev_in(rfsoc_complex_snapshot_rev_in),
    .axi4lite_sys_rev_in_we(rfsoc_complex_snapshot_rev_in_we),
    .axi4lite_sys_rev_rcs_in(rfsoc_complex_snapshot_rev_rcs_in),
    .axi4lite_sys_rev_rcs_in_we(rfsoc_complex_snapshot_rev_rcs_in_we),
    .axi4lite_sys_scratchpad_out(rfsoc_complex_snapshot_scratchpad_out),
    .axi4lite_sys_scratchpad_out_we(rfsoc_complex_snapshot_scratchpad_out_we),
    .m_axi4lite_rfdc_araddr(m_axi4lite_rfdc_araddr),
    .m_axi4lite_rfdc_arready(m_axi4lite_rfdc_arready),
    .m_axi4lite_rfdc_arvalid(m_axi4lite_rfdc_arvalid),
    .m_axi4lite_rfdc_awaddr(m_axi4lite_rfdc_awaddr),
    .m_axi4lite_rfdc_awready(m_axi4lite_rfdc_awready),
    .m_axi4lite_rfdc_awvalid(m_axi4lite_rfdc_awvalid),
    .m_axi4lite_rfdc_bready(m_axi4lite_rfdc_bready),
    .m_axi4lite_rfdc_bresp(m_axi4lite_rfdc_bresp),
    .m_axi4lite_rfdc_bvalid(m_axi4lite_rfdc_bvalid),
    .m_axi4lite_rfdc_rdata(m_axi4lite_rfdc_rdata),
    .m_axi4lite_rfdc_rready(m_axi4lite_rfdc_rready),
    .m_axi4lite_rfdc_rresp(m_axi4lite_rfdc_rresp),
    .m_axi4lite_rfdc_rvalid(m_axi4lite_rfdc_rvalid),
    .m_axi4lite_rfdc_wdata(m_axi4lite_rfdc_wdata),
    .m_axi4lite_rfdc_wready(m_axi4lite_rfdc_wready),
    .m_axi4lite_rfdc_wstrb(m_axi4lite_rfdc_wstrb),
    .m_axi4lite_rfdc_wvalid(m_axi4lite_rfdc_wvalid),
    .s_axi4lite_araddr(M_AXI_araddr),
    .s_axi4lite_arready(M_AXI_arready),
    .s_axi4lite_arvalid(M_AXI_arvalid),
    .s_axi4lite_awaddr(M_AXI_awaddr),
    .s_axi4lite_awready(M_AXI_awready),
    .s_axi4lite_awvalid(M_AXI_awvalid),
    .s_axi4lite_bready(M_AXI_bready),
    .s_axi4lite_bresp(M_AXI_bresp),
    .s_axi4lite_bvalid(M_AXI_bvalid),
    .s_axi4lite_rdata(M_AXI_rdata),
    .s_axi4lite_rready(M_AXI_rready),
    .s_axi4lite_rresp(M_AXI_rresp),
    .s_axi4lite_rvalid(M_AXI_rvalid),
    .s_axi4lite_wdata(M_AXI_wdata),
    .s_axi4lite_wready(M_AXI_wready),
    .s_axi4lite_wstrb(M_AXI_wstrb),
    .s_axi4lite_wvalid(M_AXI_wvalid)
  );


  rfsoc_complex_snapshot_ip  rfsoc_complex_snapshot_ip_inst (
    .clk(user_clk),
    .rfsoc_complex_snapshot_adcsnap0_imag_bram_addr(rfsoc_complex_snapshot_adcsnap0_imag_bram_addr),
    .rfsoc_complex_snapshot_adcsnap0_imag_bram_data_in(rfsoc_complex_snapshot_adcsnap0_imag_bram_data_in),
    .rfsoc_complex_snapshot_adcsnap0_imag_bram_data_out(rfsoc_complex_snapshot_adcsnap0_imag_bram_data_out),
    .rfsoc_complex_snapshot_adcsnap0_imag_bram_we(rfsoc_complex_snapshot_adcsnap0_imag_bram_we),
    .rfsoc_complex_snapshot_adcsnap0_imag_ctrl_user_data_out(rfsoc_complex_snapshot_adcsnap0_imag_ctrl_user_data_out),
    .rfsoc_complex_snapshot_adcsnap0_imag_status_user_data_in(rfsoc_complex_snapshot_adcsnap0_imag_status_user_data_in),
    .rfsoc_complex_snapshot_adcsnap0_real_bram_addr(rfsoc_complex_snapshot_adcsnap0_real_bram_addr),
    .rfsoc_complex_snapshot_adcsnap0_real_bram_data_in(rfsoc_complex_snapshot_adcsnap0_real_bram_data_in),
    .rfsoc_complex_snapshot_adcsnap0_real_bram_data_out(rfsoc_complex_snapshot_adcsnap0_real_bram_data_out),
    .rfsoc_complex_snapshot_adcsnap0_real_bram_we(rfsoc_complex_snapshot_adcsnap0_real_bram_we),
    .rfsoc_complex_snapshot_adcsnap0_real_ctrl_user_data_out(rfsoc_complex_snapshot_adcsnap0_real_ctrl_user_data_out),
    .rfsoc_complex_snapshot_adcsnap0_real_status_user_data_in(rfsoc_complex_snapshot_adcsnap0_real_status_user_data_in),
    .rfsoc_complex_snapshot_adcsnap1_imag_bram_addr(rfsoc_complex_snapshot_adcsnap1_imag_bram_addr),
    .rfsoc_complex_snapshot_adcsnap1_imag_bram_data_in(rfsoc_complex_snapshot_adcsnap1_imag_bram_data_in),
    .rfsoc_complex_snapshot_adcsnap1_imag_bram_data_out(rfsoc_complex_snapshot_adcsnap1_imag_bram_data_out),
    .rfsoc_complex_snapshot_adcsnap1_imag_bram_we(rfsoc_complex_snapshot_adcsnap1_imag_bram_we),
    .rfsoc_complex_snapshot_adcsnap1_imag_ctrl_user_data_out(rfsoc_complex_snapshot_adcsnap1_imag_ctrl_user_data_out),
    .rfsoc_complex_snapshot_adcsnap1_imag_status_user_data_in(rfsoc_complex_snapshot_adcsnap1_imag_status_user_data_in),
    .rfsoc_complex_snapshot_adcsnap1_real_bram_addr(rfsoc_complex_snapshot_adcsnap1_real_bram_addr),
    .rfsoc_complex_snapshot_adcsnap1_real_bram_data_in(rfsoc_complex_snapshot_adcsnap1_real_bram_data_in),
    .rfsoc_complex_snapshot_adcsnap1_real_bram_data_out(rfsoc_complex_snapshot_adcsnap1_real_bram_data_out),
    .rfsoc_complex_snapshot_adcsnap1_real_bram_we(rfsoc_complex_snapshot_adcsnap1_real_bram_we),
    .rfsoc_complex_snapshot_adcsnap1_real_ctrl_user_data_out(rfsoc_complex_snapshot_adcsnap1_real_ctrl_user_data_out),
    .rfsoc_complex_snapshot_adcsnap1_real_status_user_data_in(rfsoc_complex_snapshot_adcsnap1_real_status_user_data_in),
    .rfsoc_complex_snapshot_adcsnap2_imag_bram_addr(rfsoc_complex_snapshot_adcsnap2_imag_bram_addr),
    .rfsoc_complex_snapshot_adcsnap2_imag_bram_data_in(rfsoc_complex_snapshot_adcsnap2_imag_bram_data_in),
    .rfsoc_complex_snapshot_adcsnap2_imag_bram_data_out(rfsoc_complex_snapshot_adcsnap2_imag_bram_data_out),
    .rfsoc_complex_snapshot_adcsnap2_imag_bram_we(rfsoc_complex_snapshot_adcsnap2_imag_bram_we),
    .rfsoc_complex_snapshot_adcsnap2_imag_ctrl_user_data_out(rfsoc_complex_snapshot_adcsnap2_imag_ctrl_user_data_out),
    .rfsoc_complex_snapshot_adcsnap2_imag_status_user_data_in(rfsoc_complex_snapshot_adcsnap2_imag_status_user_data_in),
    .rfsoc_complex_snapshot_adcsnap2_real_bram_addr(rfsoc_complex_snapshot_adcsnap2_real_bram_addr),
    .rfsoc_complex_snapshot_adcsnap2_real_bram_data_in(rfsoc_complex_snapshot_adcsnap2_real_bram_data_in),
    .rfsoc_complex_snapshot_adcsnap2_real_bram_data_out(rfsoc_complex_snapshot_adcsnap2_real_bram_data_out),
    .rfsoc_complex_snapshot_adcsnap2_real_bram_we(rfsoc_complex_snapshot_adcsnap2_real_bram_we),
    .rfsoc_complex_snapshot_adcsnap2_real_ctrl_user_data_out(rfsoc_complex_snapshot_adcsnap2_real_ctrl_user_data_out),
    .rfsoc_complex_snapshot_adcsnap2_real_status_user_data_in(rfsoc_complex_snapshot_adcsnap2_real_status_user_data_in),
    .rfsoc_complex_snapshot_adcsnap3_imag_bram_addr(rfsoc_complex_snapshot_adcsnap3_imag_bram_addr),
    .rfsoc_complex_snapshot_adcsnap3_imag_bram_data_in(rfsoc_complex_snapshot_adcsnap3_imag_bram_data_in),
    .rfsoc_complex_snapshot_adcsnap3_imag_bram_data_out(rfsoc_complex_snapshot_adcsnap3_imag_bram_data_out),
    .rfsoc_complex_snapshot_adcsnap3_imag_bram_we(rfsoc_complex_snapshot_adcsnap3_imag_bram_we),
    .rfsoc_complex_snapshot_adcsnap3_imag_ctrl_user_data_out(rfsoc_complex_snapshot_adcsnap3_imag_ctrl_user_data_out),
    .rfsoc_complex_snapshot_adcsnap3_imag_status_user_data_in(rfsoc_complex_snapshot_adcsnap3_imag_status_user_data_in),
    .rfsoc_complex_snapshot_adcsnap3_real_bram_addr(rfsoc_complex_snapshot_adcsnap3_real_bram_addr),
    .rfsoc_complex_snapshot_adcsnap3_real_bram_data_in(rfsoc_complex_snapshot_adcsnap3_real_bram_data_in),
    .rfsoc_complex_snapshot_adcsnap3_real_bram_data_out(rfsoc_complex_snapshot_adcsnap3_real_bram_data_out),
    .rfsoc_complex_snapshot_adcsnap3_real_bram_we(rfsoc_complex_snapshot_adcsnap3_real_bram_we),
    .rfsoc_complex_snapshot_adcsnap3_real_ctrl_user_data_out(rfsoc_complex_snapshot_adcsnap3_real_ctrl_user_data_out),
    .rfsoc_complex_snapshot_adcsnap3_real_status_user_data_in(rfsoc_complex_snapshot_adcsnap3_real_status_user_data_in),
    .rfsoc_complex_snapshot_rfdc_m00_axis_tdata(rfsoc_complex_snapshot_rfdc_m00_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m01_axis_tdata(rfsoc_complex_snapshot_rfdc_m01_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m02_axis_tdata(rfsoc_complex_snapshot_rfdc_m02_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m03_axis_tdata(rfsoc_complex_snapshot_rfdc_m03_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m10_axis_tdata(rfsoc_complex_snapshot_rfdc_m10_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m12_axis_tdata(rfsoc_complex_snapshot_rfdc_m12_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m20_axis_tdata(rfsoc_complex_snapshot_rfdc_m20_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m21_axis_tdata(rfsoc_complex_snapshot_rfdc_m21_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m22_axis_tdata(rfsoc_complex_snapshot_rfdc_m22_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m23_axis_tdata(rfsoc_complex_snapshot_rfdc_m23_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m30_axis_tdata(rfsoc_complex_snapshot_rfdc_m30_axis_tdata),
    .rfsoc_complex_snapshot_rfdc_m32_axis_tdata(rfsoc_complex_snapshot_rfdc_m32_axis_tdata),
    .rfsoc_complex_snapshot_snap_trig_user_data_out(rfsoc_complex_snapshot_snap_trig_user_data_out)
  );

  // rfdc: rfdc
  rfsoc4x2_bd  rfsoc4x2_bd_inst (
    .adc2_clk_n(adc2_clk_n),
    .adc2_clk_p(adc2_clk_p),
    .axil_arst_n(axil_arst_n),
    .axil_rst(axil_rst),
    .clk_adc0(clk_adc0),
    .clk_adc1(clk_adc1),
    .clk_adc2(clk_adc2),
    .clk_adc3(clk_adc3),
    .irq(rfdc_irq),
    .m00_axis_tdata(rfsoc_complex_snapshot_rfdc_m00_axis_tdata),
    .m00_axis_tready(1'b1),
    .m00_axis_tvalid(m00_axis_tvalid),
    .m01_axis_tdata(rfsoc_complex_snapshot_rfdc_m01_axis_tdata),
    .m01_axis_tready(1'b1),
    .m01_axis_tvalid(m00_axis_tvalid),
    .m02_axis_tdata(rfsoc_complex_snapshot_rfdc_m02_axis_tdata),
    .m02_axis_tready(1'b1),
    .m02_axis_tvalid(m01_axis_tvalid),
    .m03_axis_tdata(rfsoc_complex_snapshot_rfdc_m03_axis_tdata),
    .m03_axis_tready(1'b1),
    .m03_axis_tvalid(m01_axis_tvalid),
    .m0_axis_aclk(m0_axis_aclk),
    .m0_axis_aresetn(axil_rst_n),
    .m10_axis_tdata(rfsoc_complex_snapshot_rfdc_m10_axis_tdata),
    .m10_axis_tready(1'b1),
    .m10_axis_tvalid(m10_axis_tvalid),
    .m12_axis_tdata(rfsoc_complex_snapshot_rfdc_m12_axis_tdata),
    .m12_axis_tready(1'b1),
    .m12_axis_tvalid(m11_axis_tvalid),
    .m1_axis_aclk(m1_axis_aclk),
    .m1_axis_aresetn(axil_rst_n),
    .m20_axis_tdata(rfsoc_complex_snapshot_rfdc_m20_axis_tdata),
    .m20_axis_tready(1'b1),
    .m20_axis_tvalid(m20_axis_tvalid),
    .m21_axis_tdata(rfsoc_complex_snapshot_rfdc_m21_axis_tdata),
    .m21_axis_tready(1'b1),
    .m21_axis_tvalid(m20_axis_tvalid),
    .m22_axis_tdata(rfsoc_complex_snapshot_rfdc_m22_axis_tdata),
    .m22_axis_tready(1'b1),
    .m22_axis_tvalid(m21_axis_tvalid),
    .m23_axis_tdata(rfsoc_complex_snapshot_rfdc_m23_axis_tdata),
    .m23_axis_tready(1'b1),
    .m23_axis_tvalid(m21_axis_tvalid),
    .m2_axis_aclk(m2_axis_aclk),
    .m2_axis_aresetn(axil_rst_n),
    .m30_axis_tdata(rfsoc_complex_snapshot_rfdc_m30_axis_tdata),
    .m30_axis_tready(1'b1),
    .m30_axis_tvalid(m30_axis_tvalid),
    .m32_axis_tdata(rfsoc_complex_snapshot_rfdc_m32_axis_tdata),
    .m32_axis_tready(1'b1),
    .m32_axis_tvalid(m31_axis_tvalid),
    .m3_axis_aclk(m3_axis_aclk),
    .m3_axis_aresetn(axil_rst_n),
    .m_axi_araddr(M_AXI_araddr),
    .m_axi_arprot(M_AXI_arprot),
    .m_axi_arready(M_AXI_arready),
    .m_axi_arvalid(M_AXI_arvalid),
    .m_axi_awaddr(M_AXI_awaddr),
    .m_axi_awprot(M_AXI_awprot),
    .m_axi_awready(M_AXI_awready),
    .m_axi_awvalid(M_AXI_awvalid),
    .m_axi_bready(M_AXI_bready),
    .m_axi_bresp(M_AXI_bresp),
    .m_axi_bvalid(M_AXI_bvalid),
    .m_axi_rdata(M_AXI_rdata),
    .m_axi_rready(M_AXI_rready),
    .m_axi_rresp(M_AXI_rresp),
    .m_axi_rvalid(M_AXI_rvalid),
    .m_axi_wdata(M_AXI_wdata),
    .m_axi_wready(M_AXI_wready),
    .m_axi_wstrb(M_AXI_wstrb),
    .m_axi_wvalid(M_AXI_wvalid),
    .pl_sys_clk(pl_sys_clk),
    .rfdc_araddr(m_axi4lite_rfdc_araddr),
    .rfdc_arready(m_axi4lite_rfdc_arready),
    .rfdc_arvalid(m_axi4lite_rfdc_arvalid),
    .rfdc_awaddr(m_axi4lite_rfdc_awaddr),
    .rfdc_awready(m_axi4lite_rfdc_awready),
    .rfdc_awvalid(m_axi4lite_rfdc_awvalid),
    .rfdc_bready(m_axi4lite_rfdc_bready),
    .rfdc_bresp(m_axi4lite_rfdc_bresp),
    .rfdc_bvalid(m_axi4lite_rfdc_bvalid),
    .rfdc_rdata(m_axi4lite_rfdc_rdata),
    .rfdc_rready(m_axi4lite_rfdc_rready),
    .rfdc_rresp(m_axi4lite_rfdc_rresp),
    .rfdc_rvalid(m_axi4lite_rfdc_rvalid),
    .rfdc_wdata(m_axi4lite_rfdc_wdata),
    .rfdc_wready(m_axi4lite_rfdc_wready),
    .rfdc_wstrb(m_axi4lite_rfdc_wstrb),
    .rfdc_wvalid(m_axi4lite_rfdc_wvalid),
    .s_axi_aclk(axil_clk),
    .s_axi_aresetn(axil_rst_n),
    .sysref_in_n(sysref_in_n),
    .sysref_in_p(sysref_in_p),
    .vin0_01_n(vin0_01_n),
    .vin0_01_p(vin0_01_p),
    .vin0_23_n(vin0_23_n),
    .vin0_23_p(vin0_23_p),
    .vin1_01_n(vin1_01_n),
    .vin1_01_p(vin1_01_p),
    .vin1_23_n(vin1_23_n),
    .vin1_23_p(vin1_23_p),
    .vin2_01_n(vin2_01_n),
    .vin2_01_p(vin2_01_p),
    .vin2_23_n(vin2_23_n),
    .vin2_23_p(vin2_23_p),
    .vin3_01_n(vin3_01_n),
    .vin3_01_p(vin3_01_p),
    .vin3_23_n(vin3_23_n),
    .vin3_23_p(vin3_23_p)
  );

  // rfsoc4x2: RFSoC4x2
  zcu216_clk_infrastructure #(
    .DIVCLK(1),
    .DIVIDE(4.0),
    .MULTIPLY(8.0),
    .PERIOD(8.138)
  ) zcu216_clk_infr_inst (
    .adc_clk(adc_clk),
    .adc_clk180(adc_clk180),
    .adc_clk270(adc_clk270),
    .adc_clk90(adc_clk90),
    .mmcm_locked(mmcm_locked),
    .pl_clk_n(pl_clk_n),
    .pl_clk_p(pl_clk_p)
  );

  // sw_reg: adcsnap0/imag/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_adcsnap0_imag_ctrl (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap0_imag_ctrl_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_adcsnap0_imag_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap0_imag_ctrl_user_data_out)
  );

  // sw_reg: adcsnap0/imag/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) rfsoc_complex_snapshot_adcsnap0_imag_status (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap0_imag_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap0_imag_status_in)
  );

  // sw_reg: adcsnap0/real/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_adcsnap0_real_ctrl (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap0_real_ctrl_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_adcsnap0_real_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap0_real_ctrl_user_data_out)
  );

  // sw_reg: adcsnap0/real/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) rfsoc_complex_snapshot_adcsnap0_real_status (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap0_real_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap0_real_status_in)
  );

  // sw_reg: adcsnap1/imag/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_adcsnap1_imag_ctrl (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap1_imag_ctrl_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_adcsnap1_imag_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap1_imag_ctrl_user_data_out)
  );

  // sw_reg: adcsnap1/imag/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) rfsoc_complex_snapshot_adcsnap1_imag_status (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap1_imag_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap1_imag_status_in)
  );

  // sw_reg: adcsnap1/real/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_adcsnap1_real_ctrl (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap1_real_ctrl_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_adcsnap1_real_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap1_real_ctrl_user_data_out)
  );

  // sw_reg: adcsnap1/real/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) rfsoc_complex_snapshot_adcsnap1_real_status (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap1_real_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap1_real_status_in)
  );

  // sw_reg: adcsnap2/imag/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_adcsnap2_imag_ctrl (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap2_imag_ctrl_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_adcsnap2_imag_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap2_imag_ctrl_user_data_out)
  );

  // sw_reg: adcsnap2/imag/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) rfsoc_complex_snapshot_adcsnap2_imag_status (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap2_imag_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap2_imag_status_in)
  );

  // sw_reg: adcsnap2/real/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_adcsnap2_real_ctrl (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap2_real_ctrl_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_adcsnap2_real_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap2_real_ctrl_user_data_out)
  );

  // sw_reg: adcsnap2/real/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) rfsoc_complex_snapshot_adcsnap2_real_status (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap2_real_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap2_real_status_in)
  );

  // sw_reg: adcsnap3/imag/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_adcsnap3_imag_ctrl (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap3_imag_ctrl_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_adcsnap3_imag_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap3_imag_ctrl_user_data_out)
  );

  // sw_reg: adcsnap3/imag/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) rfsoc_complex_snapshot_adcsnap3_imag_status (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap3_imag_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap3_imag_status_in)
  );

  // sw_reg: adcsnap3/real/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_adcsnap3_real_ctrl (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap3_real_ctrl_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_adcsnap3_real_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap3_real_ctrl_user_data_out)
  );

  // sw_reg: adcsnap3/real/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) rfsoc_complex_snapshot_adcsnap3_real_status (
    .IP_BUS(rfsoc_complex_snapshot_adcsnap3_real_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_adcsnap3_real_status_in)
  );

  // sw_reg: snap_trig
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) rfsoc_complex_snapshot_snap_trig (
    .IP_BUS(rfsoc_complex_snapshot_snap_trig_out),
    .IP_BUS_VALID(rfsoc_complex_snapshot_snap_trig_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(rfsoc_complex_snapshot_snap_trig_user_data_out)
  );

  // sys_block: RFSoC4x2
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) sys_block_counter_cdc_inst (
    .IP_BUS(rfsoc_complex_snapshot_clkcounter_cdc),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(rfsoc_complex_snapshot_clkcounter_in)
  );


  sys_block_counter #(
    .DATA_WIDTH(32)
  ) sys_block_counter_inst (
    .count_out(rfsoc_complex_snapshot_clkcounter_cdc),
    .en(1),
    .user_clk(user_clk),
    .user_rst(user_rst),
    .we(rfsoc_complex_snapshot_clkcounter_we)
  );


/*
                   _                                  _       
     /\           (_)                                | |      
    /  \   ___ ___ _  __ _ _ __  _ __ ___   ___ _ __ | |_ ___ 
   / /\ \ / __/ __| |/ _` | '_ \| '_ ` _ \ / _ \ '_ \| __/ __|
  / ____ \\__ \__ \ | (_| | | | | | | | | |  __/ | | | |_\__ \ 
 /_/    \_\___/___/_|\__, |_| |_|_| |_| |_|\___|_| |_|\__|___/
                      __/ |                                   
                     |___/                                    
*/
  // rfdc: rfdc
  assign m0_axis_aclk = adc_clk;
  assign m1_axis_aclk = adc_clk;
  assign m2_axis_aclk = adc_clk;
  assign m3_axis_aclk = adc_clk;
  // rfsoc4x2: RFSoC4x2
  assign axil_clk = pl_sys_clk;
  assign axil_rst_n = axil_arst_n;
  assign sys_clk = pl_sys_clk;
  assign sys_rst = ~axil_arst_n;
  // xsg: RFSoC4x2
  assign user_clk = adc_clk;
  assign user_clk180 = adc_clk180;
  assign user_clk270 = adc_clk270;
  assign user_clk90 = adc_clk90;


endmodule